In [2]:
import numpy as np

In [3]:
empty = np.empty((2, 3))
print(empty)
print("--------------")
print(empty[0])

[[0.00000000e+000 0.00000000e+000 1.69121096e-306]
 [8.01092457e-307 1.89146896e-307 7.56571288e-307]]
--------------
[0.00000000e+000 0.00000000e+000 1.69121096e-306]


In [4]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [5]:
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [6]:
odd = np.arange(1, 23, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [7]:
diff = np.arange(0, 23, 3)
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [8]:
lin = np.linspace(0, 10, num=5)
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
lin = np.linspace(0, -10, num=5)
lin

array([  0. ,  -2.5,  -5. ,  -7.5, -10. ])

In [10]:
lin.dtype

dtype('float64')

In [11]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [12]:
arr = np.array([1, 2, 5, 1, 4, 4])
arr

array([1, 2, 5, 1, 4, 4])

In [13]:
np.sort(arr)

array([1, 1, 2, 4, 4, 5])

In [14]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

In [15]:
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [17]:
z = np.concatenate((x, y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
x = np.array([[1, 2], [3, 4]])
w = np.array([[5, 1], [7, 1]])

In [22]:
z1 = np.concatenate((x, w))
z1

array([[1, 2],
       [3, 4],
       [5, 1],
       [7, 1]])

In [23]:
z1 = np.concatenate((x, w), axis=1)
z1

array([[1, 2, 5, 1],
       [3, 4, 7, 1]])

In [24]:
x.ndim

2

In [25]:
array_example = np.array([[[0,1,2,3],
                            [4,5,6,7]],
                           [[0,1,2,3],
                            [4,5,6,7]],
                           [[0,1,2,3],
                            [4,5,6,7]]])
array_example.ndim

3

In [26]:
len(array_example)

3

In [27]:
array_example.size

24

In [28]:
array_example.dtype

dtype('int32')

In [29]:
array_example.shape

(3, 2, 4)

In [37]:
a = np.array([[[0,1,2,3]],
              [[4,5,6,7]],
              [[0,1,2,3]]])
a.shape

(3, 1, 4)

In [38]:
a1 = a.reshape(6, 2)
a1.shape

(6, 2)

In [39]:
a

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [40]:
a1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3]])

In [41]:
a1.reshape(3,1,4)

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [42]:
a = np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [48]:
b = a[np.newaxis, :]
b.shape

(1, 8)

In [50]:
c = a[:, np.newaxis]
c.shape

(8, 1)

In [51]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
a[2:5]

array([3, 4, 5])

In [53]:
a[-4:]

array([5, 6, 7, 8])

In [54]:

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
b[0]

array([1, 2, 3, 4])

In [56]:
b[1:, 1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [57]:
b[b < 5]

array([1, 2, 3, 4])

In [58]:
b[b < 2]

array([1])

In [59]:
b[b % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [60]:
b[b % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [63]:
b[(b > 2) & (b < 11)] 

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
b[(b > 2) & (b < 11) & (b % 2 == 0)]

array([ 4,  6,  8, 10])

In [64]:
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])