## *NumPuy Indexing and Slicing*

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [3]:
a[0]

1

In [4]:
a[-1]

5

In [10]:
a[1:]

array([2, 3, 4, 5])

In [11]:
a[1:5]

array([2, 3, 4, 5])

In [5]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [6]:
b[2]

4

In [12]:
c = b.reshape(3, 2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [9]:
c[0]

array([0, 2, 4])

In [13]:
c[c < 5]

array([0, 2, 4])

In [14]:
c[(c < 5) & (c > 10)]

array([], dtype=int32)