In [1]:
import numpy as np

In [2]:
a = np.arange(0, 222, 2)
a

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220])

In [3]:
arr1 = a[40:45]
arr1

array([80, 82, 84, 86, 88])

In [4]:
a = np.array([1, 2, 3, 4, 6, 7])
b = np.array([8, 9, 10, 11, 12, 13])

In [5]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  6,  7],
       [ 8,  9, 10, 11, 12, 13]])

In [6]:
d = np.hstack((a,b))
d

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13])

In [9]:
d = d.reshape(2, 6)
d

array([[ 1,  2,  3,  4,  6,  7],
       [ 8,  9, 10, 11, 12, 13]])