## *Matrices*

In [1]:
import numpy as np

In [2]:
# create a 2x3 matrix
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a[1]

array([4, 5, 6])

In [7]:
b = np.arange(0, 100, 2).reshape(5, 10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [8]:
b[1]

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [ ]:
b[:,:]

In [9]:
c = b[1:3, 3:5]

array([[26, 28],
       [46, 48]])

In [11]:
b.max()

98

In [12]:
b.min()

0

In [13]:
b.sum()

2450

In [15]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [16]:
b.max(axis=0)

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [17]:
b.max(axis=1)

array([18, 38, 58, 78, 98])

In [18]:
m = np.arange(0, 20, 2).reshape(5, 2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [19]:
m + np.array([20, 22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [20]:
np.vstack((m, np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])