In [1]:
import numpy as np

In [10]:
a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [11]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [13]:
a3 = a[:, np.newaxis]
print(a3)
a3.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [14]:
a4 = a2[np.newaxis, :]
print(a4)
a4.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

In [15]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([(1, 2, 3, 4, 5, 6), (4, 5, 6, 7, 8, 9)])

In [18]:
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [27]:
a.dtype

dtype('int32')

In [19]:
print(b)
b.shape

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


(2, 6)

In [28]:
b.dtype

dtype('int32')

## *Create Arrays with NumPy*

In [22]:
zeros = np.zeros((14, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
ones = np.ones((2, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
ones.dtype

dtype('float64')

In [24]:
full = np.full((2,5), 5)
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [30]:
full.dtype

dtype('int32')

In [31]:
type(full)

numpy.ndarray

In [25]:
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## *Array Attributes*

In [32]:
a.shape

(6,)

In [33]:
len(a)

6

In [34]:
a.ndim

1

In [35]:
b.ndim

2

In [36]:
a.size

6

## *Basic Operation*

In [38]:
a

array([1, 2, 3, 4, 5, 6])

In [39]:
b

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [40]:
sub = a - b
sub

array([[ 0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3]])

In [41]:
add = a + b
add

array([[ 2,  4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13, 15]])

In [44]:
add1 = np.add(a, b)
add1

array([[ 2,  4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13, 15]])

In [45]:
mult = a * b
mult

array([[ 1,  4,  9, 16, 25, 36],
       [ 4, 10, 18, 28, 40, 54]])

In [46]:
div = a/b
div

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667]])

In [47]:
sq = a ** 2
sq

array([ 1,  4,  9, 16, 25, 36])